-- Generated by scripts/export/export.mjs from https://dresswithbless.foorweb.store
-- 3 products. Run once: products have no natural key, so re-running duplicates them.
begin;

-- Categories missing from our schema, appended after the existing ones.
insert into public.categories (name, slug, sort_order)
select 'Ensembles', 'ensembles', coalesce(max(sort_order), 0) + 1 from public.categories
on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order)
select 'Accessories', 'accessories', coalesce(max(sort_order), 0) + 1 from public.categories
on conflict (slug) do nothing;

-- Products
insert into public.products (name, description, category_id, size, price, images, is_new, is_sold)
values (
  'TOT BAG',
  'tot bag noir',
  (select id from public.categories where slug = 'accessories'),
  null,
  14000,
  array['https://4oey1j8tyx.ufs.sh/f/rbKe0tEW4UNkWGwnHCNJPjIyK1V5zixF6crnfCZ8tUMdhpk0']::text[],
  true,
  false
); -- source VuQUfSYAGte2HKQuzPP2
insert into public.products (name, description, category_id, size, price, images, is_new, is_sold)
values (
  'ensemble velour',
  'ensemble velour jaune moutarde
taille M',
  (select id from public.categories where slug = 'ensembles'),
  'M',
  14000,
  array['https://4oey1j8tyx.ufs.sh/f/rbKe0tEW4UNkXUUPNURYDwWuJ1kgdREVlc3MbfTH4oAO2tQP']::text[],
  true,
  false
); -- source b0b4e3WNFq7XIvzmY0UG
insert into public.products (name, description, category_id, size, price, images, is_new, is_sold)
values (
  'veste maron',
  'VESTE MARON',
  (select id from public.categories where slug = 'jackets'),
  null,
  14000,
  array['https://4oey1j8tyx.ufs.sh/f/rbKe0tEW4UNkE2G9SqXqYL9hgwmHXPpOt0rQ762kDMWNx3dK']::text[],
  true,
  false
); -- source tRfNrgfIQT4cYGTIJHgS

commit;
